### ISSUE TITLE
Calculated property typo require fixing.

### ISSUE THREAD

**Issue by albert-widjaja** [claranet/ClaranetHub#1]
​
Hi mate, there is a slight typo in the Calculated Property:

Old code with a comma:

`$STATES = ($JOBS | Select-Object Id, Name, IsScheduleEnabled, @{ N = "IsSchedulable", E = { $_.IsSchedulable() } })
`

Updated code with a semicolon:

`$STATES = ($JOBS | Select-Object Id, Name, IsScheduleEnabled, @{ N = "IsSchedulable"; E = { $_.IsSchedulable() } })
`

I hope that helps.

​

**Comment by arogarth** [comment]
Thanks, it is fixed
